language: php
git:
    depth: 5
install:
    - composer install
matrix:
    fast_finish: true
    allow_failures:
        -   php: 7.3
php:
    - 7.1
    - 7.2
    - 7.3
script:
    - mkdir -p build
    - phpdbg -qrr -f vendor/phpspec/phpspec/bin/phpspec --no-interaction --config=phpspec_travis_coverage.yml run
after_success:
    - travis_retry composer require --dev php-coveralls/php-coveralls\
        && php vendor/bin/php-coveralls -v
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar\
        && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
