language: php
install:
  - composer selfupdate
  - composer install
matrix:
  allow_failures:
    - php: hhvm
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
